// Generated by gencpp from file k21_controller/Lifter.msg
// DO NOT EDIT!


#ifndef K21_CONTROLLER_MESSAGE_LIFTER_H
#define K21_CONTROLLER_MESSAGE_LIFTER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace k21_controller
{
template <class ContainerAllocator>
struct Lifter_
{
  typedef Lifter_<ContainerAllocator> Type;

  Lifter_()
    : lifter_point(0.0)
    , gripper(0.0)  {
    }
  Lifter_(const ContainerAllocator& _alloc)
    : lifter_point(0.0)
    , gripper(0.0)  {
  (void)_alloc;
    }



   typedef double _lifter_point_type;
  _lifter_point_type lifter_point;

   typedef double _gripper_type;
  _gripper_type gripper;





  typedef boost::shared_ptr< ::k21_controller::Lifter_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::k21_controller::Lifter_<ContainerAllocator> const> ConstPtr;

}; // struct Lifter_

typedef ::k21_controller::Lifter_<std::allocator<void> > Lifter;

typedef boost::shared_ptr< ::k21_controller::Lifter > LifterPtr;
typedef boost::shared_ptr< ::k21_controller::Lifter const> LifterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::k21_controller::Lifter_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::k21_controller::Lifter_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::k21_controller::Lifter_<ContainerAllocator1> & lhs, const ::k21_controller::Lifter_<ContainerAllocator2> & rhs)
{
  return lhs.lifter_point == rhs.lifter_point &&
    lhs.gripper == rhs.gripper;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::k21_controller::Lifter_<ContainerAllocator1> & lhs, const ::k21_controller::Lifter_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace k21_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::k21_controller::Lifter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::k21_controller::Lifter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::k21_controller::Lifter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::k21_controller::Lifter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::k21_controller::Lifter_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::k21_controller::Lifter_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::k21_controller::Lifter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a3137a64e8cabd06e461b82358bf017";
  }

  static const char* value(const ::k21_controller::Lifter_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a3137a64e8cabd0ULL;
  static const uint64_t static_value2 = 0x6e461b82358bf017ULL;
};

template<class ContainerAllocator>
struct DataType< ::k21_controller::Lifter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "k21_controller/Lifter";
  }

  static const char* value(const ::k21_controller::Lifter_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::k21_controller::Lifter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 lifter_point\n"
"float64 gripper\n"
;
  }

  static const char* value(const ::k21_controller::Lifter_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::k21_controller::Lifter_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lifter_point);
      stream.next(m.gripper);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Lifter_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::k21_controller::Lifter_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::k21_controller::Lifter_<ContainerAllocator>& v)
  {
    s << indent << "lifter_point: ";
    Printer<double>::stream(s, indent + "  ", v.lifter_point);
    s << indent << "gripper: ";
    Printer<double>::stream(s, indent + "  ", v.gripper);
  }
};

} // namespace message_operations
} // namespace ros

#endif // K21_CONTROLLER_MESSAGE_LIFTER_H
