// Generated by gencpp from file k21_controller/VelCmd.msg
// DO NOT EDIT!


#ifndef K21_CONTROLLER_MESSAGE_VELCMD_H
#define K21_CONTROLLER_MESSAGE_VELCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace k21_controller
{
template <class ContainerAllocator>
struct VelCmd_
{
  typedef VelCmd_<ContainerAllocator> Type;

  VelCmd_()
    : Vx(0.0)
    , Vy(0.0)
    , w(0.0)  {
    }
  VelCmd_(const ContainerAllocator& _alloc)
    : Vx(0.0)
    , Vy(0.0)
    , w(0.0)  {
  (void)_alloc;
    }



   typedef double _Vx_type;
  _Vx_type Vx;

   typedef double _Vy_type;
  _Vy_type Vy;

   typedef double _w_type;
  _w_type w;





  typedef boost::shared_ptr< ::k21_controller::VelCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::k21_controller::VelCmd_<ContainerAllocator> const> ConstPtr;

}; // struct VelCmd_

typedef ::k21_controller::VelCmd_<std::allocator<void> > VelCmd;

typedef boost::shared_ptr< ::k21_controller::VelCmd > VelCmdPtr;
typedef boost::shared_ptr< ::k21_controller::VelCmd const> VelCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::k21_controller::VelCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::k21_controller::VelCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::k21_controller::VelCmd_<ContainerAllocator1> & lhs, const ::k21_controller::VelCmd_<ContainerAllocator2> & rhs)
{
  return lhs.Vx == rhs.Vx &&
    lhs.Vy == rhs.Vy &&
    lhs.w == rhs.w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::k21_controller::VelCmd_<ContainerAllocator1> & lhs, const ::k21_controller::VelCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace k21_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::k21_controller::VelCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::k21_controller::VelCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::k21_controller::VelCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::k21_controller::VelCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::k21_controller::VelCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::k21_controller::VelCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::k21_controller::VelCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc80fc0c33bfc67846d488513b7c90a4";
  }

  static const char* value(const ::k21_controller::VelCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc80fc0c33bfc678ULL;
  static const uint64_t static_value2 = 0x46d488513b7c90a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::k21_controller::VelCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "k21_controller/VelCmd";
  }

  static const char* value(const ::k21_controller::VelCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::k21_controller::VelCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 Vx\n"
"float64 Vy\n"
"float64 w\n"
;
  }

  static const char* value(const ::k21_controller::VelCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::k21_controller::VelCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Vx);
      stream.next(m.Vy);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::k21_controller::VelCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::k21_controller::VelCmd_<ContainerAllocator>& v)
  {
    s << indent << "Vx: ";
    Printer<double>::stream(s, indent + "  ", v.Vx);
    s << indent << "Vy: ";
    Printer<double>::stream(s, indent + "  ", v.Vy);
    s << indent << "w: ";
    Printer<double>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // K21_CONTROLLER_MESSAGE_VELCMD_H
